language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
  - cargo fmt -- --check
  - cargo clippy --all-features
