[package]
name = "yajlish"
version = "0.1.0"
authors = ["Boyd Johnson <johnson.boyd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.0"
nom = { version = "6.0.0-alpha1", features = ["regexp"] }

[dev-dependencies]
pretty_assertions = "^0.6"
proptest = "^0.10"
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"



[features]
ndjson = []
